### ISSUE TITLE
[nano] decor example is not working

### ISSUE THREAD

**Issue by g4s8** [jcabi/jcabi-log#104]
I tried to use `[nano]` decor example from this page https://log.jcabi.com/decors.html

```java
    final long start = System.nanoTime();
    // some operations
    Logger.debug(
      this,
      "done in %[nano]d",
      System.nanoTime() - start
    );
```

but it throws an exception:
```

java.util.IllegalFormatConversionException: d != com.jcabi.log.NanoDecor

	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302)
	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2793)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2747)
	at java.util.Formatter.format(Formatter.java:2520)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at com.jcabi.log.Logger.format(Logger.java:128)
	at com.jcabi.log.Logger.infoForced(Logger.java:247)
```

**Comment by yegor256** [comment]
@g4s8 try `"done in %[nano]s"`
