### ISSUE TITLE
All jcabi libraries are not working with JDK13 because logger uses invalid refrelction access

### ISSUE THREAD

**Issue by g4s8** [jcabi/jcabi-log#107]
Logger is trying to change some static final reference via reflection:
```java
    private static void setFinalStatic(final Field field, final Object value)
        throws NoSuchFieldException, IllegalAccessException {
        field.setAccessible(true);
        final Field modifiers = Field.class.getDeclaredField("modifiers");
        modifiers.setAccessible(true);
        modifiers.setInt(field, field.getModifiers() & ~Modifier.FINAL);
        field.set(null, value);
    }
```
what causes an error on JDK13:
```
Exception in thread "main" java.lang.IllegalStateException: java.lang.NoSuchFieldException: modifiers
	at com.jcabi.log.Logger.logger(Logger.java:413)
	at com.jcabi.log.Logger.isDebugEnabled(Logger.java:267)
	at com.jcabi.log.Logger.debug(Logger.java:174)
	at com.jcabi.aspects.aj.ImmutabilityChecker.check(ImmutabilityChecker.java:122)
	at com.jcabi.aspects.aj.ImmutabilityChecker.after(ImmutabilityChecker.java:71)
	at com.jcabi.s3.cached.CdRegion.<init>(CdRegion.java:62)

Caused by: java.lang.NoSuchFieldException: modifiers
	at java.base/java.lang.Class.getDeclaredField(Class.java:2412)
	at com.jcabi.log.Logger.setFinalStatic(Logger.java:386)
	at com.jcabi.log.Logger.logger(Logger.java:411)
	... 6 more
```
The problem is that almost all jcabi dependencies uses jcabi-log therefore all of them can't be used with JDK13.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 I think we can safely remove this piece of code. Would you be able to submit a PR please?

**Comment by yegor256** [comment]
@g4s8 I think the latest version works just fine, tested with JDK 17
