### ISSUE TITLE
Let's make VerboseProcess closeable

### ISSUE THREAD

**Issue by longtimeago** [jcabi/jcabi-log#38]
I've tried to switch thindeck project on jcabi-log 0.15 and got a lot of exceptions in test traces, like this one

```
[INFO] com.jcabi.ssh.SSH: $ cd /tmp/1414850462933-0;if [ -f existing-host.hosts.conf ];then if [[ $(grep '10.0.0.2:80' existing-host.hosts.conf) != *10.0.0.2:80* ]];then sed -i.bak -r 's/}/    server 10.0.0.2:80;\n}/' existing-host.hosts.conf;fi;rm existing-host.hosts.conf.bak;else printf 'upstream existing-host_servers {\n    server 10.0.0.2:80;\n}' > existing-host.hosts.conf;fi;pkill -HUP -f nginx
[WARN] com.jcabi.log.VerboseRunnable: escalated exception: java.lang.IllegalStateException: java.io.IOException: Stream closed
        at com.jcabi.log.VerboseRunnable$1.run(VerboseRunnable.java:139)
        at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:272)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:154)
        at java.io.BufferedReader.readLine(BufferedReader.java:317)
        at java.io.BufferedReader.readLine(BufferedReader.java:382)
        at com.jcabi.log.VerboseProcess$Monitor.call(VerboseProcess.java:357)
        at com.jcabi.log.VerboseProcess$Monitor.call(VerboseProcess.java:314)
        at com.jcabi.log.VerboseRunnable$1.run(VerboseRunnable.java:133)
        ... 2 more
```

It supposed to be fixed in scope of https://github.com/jcabi/jcabi-log/issues/36 but wasn't
Issue is also a blocks others, at least this one https://github.com/jcabi/jcabi-mysql-maven-plugin/issues/30

So, let's make VerboseProcess responsible for closing 2 internal monitors and then closing decorated process. IMHO, good idea if VerboseProcess would implement Closable

See my comment below https://github.com/jcabi/jcabi-log/issues/38#issuecomment-61420573

**Comment by dmarkov** [comment]
the last puzzle `38-9367cb1e`/#46 solved
